version: '3'

services:
  dbos:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: sheersh
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: projectdb

    volumes: 
      - mysqldb:/var/lib/mysql
    
  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on: 
      - dbos
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: sheersh
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: projectdb
    volumes:
      - wordpressdb:/var/www/html

volumes:
  mysqldb:
  wordpressdb:

