- name: Transfer and execute a script.
  hosts: test
  tasks:
     - name: Transfer the script
       copy: src=sript.sh dest=/home/sheersh mode=771
       register: update
       failed_when: "'FAILED' in update.stderr"
  
     - name: "test cronjob"
       cron:
        name: "cronjob"
        state: present
        minute: "*/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: 'sh script.sh'
